name: Dispatch to Knowledge Forest

on:
  push:
    branches:
      - main

jobs:
    dispatch:
        name: Repository Dispatch
        runs-on: ubuntu-latest
        steps:
          - name: Dispatch Knowledge Forest  
            uses: peter-evans/repository-dispatch@v3
            with:
                token: ${{secrets.PAT}}
                repository: Gekokeitaro/my-knowledge-forest
                event-type: deploy
            
