name: Dispatch to Knowledge Forest

on:
  push:
    branches:
      - main

jobs:
    dispatch:
        name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
            repository: Gekokeitaro/my-knowledge-forest
            ref: main
            event_type: deploy
            
